[package]
name = "rust-obs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
obws = "0.11.5"
once_cell = "1.19.0"
serde = "1.0.200"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
